# The fpgfile that the SNAP boards have to be programmed with. 
# Set the 'p' flag with calling the init script to program the boards.
fpgfile: '/home/hera/src/hera_corr_f/snap_fengine/outputs/snap_fengine_2018-06-07_0929.fpg'

# The UDP port where F-Engine data is sent. This should match what the X-Engines are expecting.
dest_port: 8511

sync: 'pps'

# Turn on the noise generator for testing
noise: False

initialize: False

# Disable transmission for all fengines
eth: False

tvg: False

# The F-Engines in a design.
# Keys should be resolvable hostnames
fengines:
    my-fengine-hostname1:
        # Which walsh pattern should this SNAP board use.
        # Currently unimplemented. Maybe should be a per-pol array
        phase_switch_index: 0
        # Correlator-style antenna indices
        # This should be a range of <=48 antennas. If <48, it should be a
        # multiple of 3.
        # NB, as currently implemented, the three elements should be consecutive,
        # with the first a multiple of 3.
        ants: [48,60]
    my-fengine-hostname2:
        # Which walsh pattern should this SNAP board use.
        # Currently unimplemented. Maybe should be a per-pol array
        phase_switch_index: 0
        # Correlator-style antenna indices
        # This should be a three-element list, unique among the system.
        # NB, as currently implemented, the three elements should be consecutive,
        # with the first a multiple of 3.
        ants: [0,47]

# The X-Engines in a design.
# The maximum number of X-Engines is 16.
# Each X-engine accepts 384 channels.
# Only channels defined here will be sent out by F-Engines. Other
# channels are not sent anywhere.

# Data can be alloted to (48/num_ants_per_feng) 
# number of X-engines. 384 channels are sent to 
# each Xeng specified.

xengines:
    # Zero-indexed X-engine number
    0:
        # IP/MAC address where even and odd time-sample pairs are sent
        # The correlator design assumes these are two interfaces on the same physical X-box
        even:
           ip: "10.80.40.197"
           mac: 0x02020a5028c5
        odd:
           ip: "10.80.40.206"
           mac: 0x02020a5028ce
        # Channels to send to this X-Engine.
        # [A,B] implies channels np.arange(A,B) will be sent.
        # Should be 384 channels. YMMV with other configurations, which may be useful for
        # throughput testing but are otherwise invalid.
        chan_range: [1536, 1920]
    1:
        even:
           ip: "10.80.40.229"
           mac: 0x02020a5028e5
        odd:
           ip: "10.80.40.238"
           mac: 0x02020a5028ee
        chan_range: [1920, 2304]
