# correlator configuration file

# common to all correlator machines
common:
  big_nbytes: 402653184
  nbytes_many: 49152000
  nbytes_many2: 943718400
  nbytes_final: 42240000
  # nbytes_final: 417792000
  nsamps: 49152
  nwait: 63000
  nn: 384
  log_dir: /mnt/nfs/runtime/tmplog
  capture:
    cmd: /usr/local/dsaX/bin/dsaX_correlator_udpdb_thread
    port: 4011
    filename: /mnt/nfs/code/dsaX/src/correlator_header_dsaX.txt
    k: caca
    b: 1
  final:
    cmd: /usr/local/dsaX/bin/dsaX_writevis
    log: /mnt/nfs/runtime/tmplog/final_log_
    c: 13
  dbnic:
    cmd: /usr/local/dsaX/bin/dsaX_dbnic
  nicdb:
    cmd: /usr/local/dsaX/bin/dsaX_nicdb
  fanout:
    cmd: /usr/local/dsaX/bin/dsaX_correlator_fanout
    c: 2
  massager:
    cmd: /usr/local/dsaX/bin/dsaX_fancy
    c: 14
  cpscr:
    cmd: /usr/local/dsaX/bin/cpscr.bash
    log: /mnt/nfs/runtime/tmplog/cpscr_log_
  ar_cmd: /usr/local/dsaX/bin/dsaX_single
  ar:
    - k: adbd
      o: bdad
      c: 24
    - k: adcd
      o: bdcd
      c: 25
    - k: addd
      o: bddd
      c: 26
    - k: aaaa
      o: bbbb
      c: 27
    - k: aaba
      o: bbab
      c: 28
  buffer:
    - k: caca
      b: 402653184
      c: 0
      n: 8
    - k: dbda
      b: 49152000
      c: 0
      n: 4
    - k: dcda
      b: 49152000
      c: 0
      n: 4
    - k: ddda
      b: 49152000
      c: 0
      n: 4
    - k: ebda
      b: 49152000
      c: 0
      n: 4
    - k: ecda
      b: 49152000
      c: 0
      n: 4
    - k: adbd
      b: 49152000
      c: 1
      n: 4
    - k: adcd
      b: 49152000
      c: 1
      n: 4
    - k: addd
      b: 49152000
      c: 1
      n: 4
    - k: aaaa
      b: 49152000
      c: 1
      n: 4
    - k: aaba
      b: 49152000
      c: 1
      n: 4
    - k: bdad
      b: 98304000
      c: 1
      n: 4
    - k: bdcd
      b: 98304000
      c: 1
      n: 4
    - k: bddd
      b: 98304000
      c: 1
      n: 4
    - k: bbbb
      b: 98304000
      c: 1
      n: 4
    - k: bbab
      b: 98304000
      c: 1
      n: 4
    - k: eada
      b: 42240000
      c: 1
      n: 4
machine:
  dsamaster:
    capture:
      ip: 10.10.5.1
    dbnic_port: 7016
    dbnic:
      - ip: 10.10.4.1
        c: 3
        k: dbda
      - ip: 10.10.4.2
        c: 4
        k: dcda
      - ip: 10.10.4.3
        c: 5
        k: ddda
      - ip: 10.10.4.4
        c: 6
        k: ebda
      - ip: 10.10.5.5
        c: 7
        k: ecda
    nicdb:
      - ip: 10.10.4.1
        port: 7016
        c: 8
        k: adbd
      - ip: 10.10.4.1
        port: 7015
        c: 9
        k: adcd
      - ip: 10.10.4.1
        port: 7014
        c: 10
        k: addd
      - ip: 10.10.4.1
        port: 7013
        c: 11
        k: aaaa
      - ip: 10.10.4.1
        port: 7012
        c: 12
        k: aaba
    final:
      ip: 10.10.1.1
      filename: /home/user/data/run1/dsa0
      o: 1487.27539

  dsa1:
    capture:
      ip: 10.10.6.1
    dbnic_port: 7015
    dbnic:
      - ip: 10.10.4.1
        c: 3
        k: dbda
      - ip: 10.10.4.2
        c: 4
        k: dcda
      - ip: 10.10.4.3
        c: 5
        k: ddda
      - ip: 10.10.4.4
        c: 6
        k: ebda
      - ip: 10.10.4.5
        c: 7
        k: ecda
    nicdb_ip: 10.10.4.2
    nicdb:
      - port: 7016
        ip: 10.10.4.2
        c: 8
        k: adbd
      - port: 7015
        ip: 10.10.4.2
        c: 9
        k: adcd
      - port: 7014
        ip: 10.10.4.2
        c: 10
        k: addd
      - port: 7013
        ip: 10.10.4.2
        c: 11
        k: aaaa
      - port: 7012
        ip: 10.10.4.2
        c: 12
        k: aaba
    final:
      ip: 10.10.1.7
      filename: /home/user/data/run1/dsa1
      o: 1456.75781

  dsa2:
    capture:
      ip: 10.10.7.1
    dbnic_port: 7014
    dbnic:
      - ip: 10.10.4.1
        c: 3
        k: dbda
      - ip: 10.10.4.2
        c: 4
        k: dcda
      - ip: 10.10.4.3
        c: 5
        k: ddda
      - ip: 10.10.4.4
        c: 6
        k: ebda
      - ip: 10.10.4.5
        c: 7
        k: ecda
    nicdb_ip: 10.10.4.3
    nicdb:
      - port: 7016
        ip: 10.10.4.3
        c: 8
        k: adbd
      - port: 7015
        ip: 10.10.4.3
        c: 9
        k: adcd
      - port: 7014
        ip: 10.10.4.3
        c: 10
        k: addd
      - port: 7013
        ip: 10.10.4.3
        c: 11
        k: aaaa
      - port: 7012
        ip: 10.10.4.3
        c: 12
        k: aaba
    final:
      ip: 10.10.1.8
      filename: /home/user/data/run1/dsa2
      o: 1426.24023

  dsa3:
    capture:
      ip: 10.10.8.1
    dbnic_port: 7013
    dbnic:
      - ip: 10.10.4.1
        c: 3
        k: dbda
      - ip: 10.10.4.2
        c: 4
        k: dcda
      - ip: 10.10.4.3
        c: 5
        k: ddda
      - ip: 10.10.4.4
        c: 6
        k: ebda
      - ip: 10.10.4.5
        c: 7
        k: ecda
    nicdb_ip: 10.10.4.4
    nicdb:
      - port: 7016
        ip: 10.10.4.4
        c: 8
        k: adbd
      - port: 7015
        ip: 10.10.4.4
        c: 9
        k: adcd
      - port: 7014
        ip: 10.10.4.4
        c: 10
        k: addd
      - port: 7013
        ip: 10.10.4.4
        c: 11
        k: aaaa
      - port: 7012
        ip: 10.10.4.4
        c: 12
        k: aaba
    final:
      ip: 10.10.1.9
      filename: /home/user/data/run1/dsa3
      o: 1395.72266

  dsa4:
    capture:
      ip: 10.10.9.1
    dbnic_port: 7012
    dbnic:
      - ip: 10.10.4.1
        c: 3
        k: dbda
      - ip: 10.10.4.2
        c: 4
        k: dcda
      - ip: 10.10.4.3
        c: 5
        k: ddda
      - ip: 10.10.4.4
        c: 6
        k: ebda
      - ip: 10.10.4.5
        c: 7
        k: ecda
    nicdb_ip: 10.10.4.5
    nicdb:
      - port: 7016
        ip: 10.10.4.5
        c: 8
        k: adbd
      - port: 7015
        ip: 10.10.4.5
        c: 9
        k: adcd
      - port: 7014
        ip: 10.10.4.5
        c: 10
        k: addd
      - port: 7013
        ip: 10.10.4.5
        c: 11
        k: aaaa
      - port: 7012
        ip: 10.10.4.5
        c: 12
        k: aaba
    final:
      ip: 10.10.1.10
      filename: /home/user/data/run1/dsa4
      o: 1365.20508
