#
# For each fengine, specify the host ip address (host_ip), destination port (dest_port),
# the antenna numbers it is processing (ants). 
#
# The following booleans can also be set- 
# if it needs to be initialized (init), 
# if you want to set noise (noise), 
# or test vector (tvg) input and if you want it to 
# send data over ethernet (eth).
#
# If a specific boolean task needs to be implemented on all fengines, you can 
# set it as a global parameter.
#
# NB: If fengine antennas are not specified, they will be alloted according the order in 
# which they are presented here.

# You can set the following global parameters for all fengines 
# or enable them for only some fengines. The global parameters 
# overrride the individual fengine settings.

# You can sync the fengines using an external PPS signal
# or manually using a software register. 
# Choices: 'pps', 'manual', False (default: 'pps')
sync: 'pps'

# The test vector generator can operate in multiple modes:
# 'const_ants' : Writes a different constant value 
#                to all channels of an antenna (both pols).
# 'const_pols' : Write a different constant value  
#                to both pols of an antenna.
# 'ramp'       : Write the same ramp to all pols.
# 'ramp_pols'  : Write a different ramp to each pol.
# False        : Do not set the test vector (default) 
tvg: False

# Manual sync
sync: pps

# Run initialization
initialize: True

# Enable/disable transmission for all fengines
eth: True

# Specify a full path to an F-Engine fpg files
fpgfile: '/home/ubuntu/proj/dsa110-shell/SNAP_control/config/snap_fengine_nophase_2020-08-13_0941.fpg'

# Destination port for SNAP data
dest_port: 4011

fengines:
    snap00.sas.pvt:
        ants: [0, 1, 2]
        sync_delay: 0
    snap01.sas.pvt:
        ants: [3, 4, 5]
        sync_delay: 20
    snap02.sas.pvt:
        ants: [6, 7, 8]
        sync_delay: 40
    snap03.sas.pvt:
        ants: [9, 10, 11]
        sync_delay: 60
    snap04.sas.pvt:
        ants: [12, 13, 14]
        sync_delay: 80
    snap05.sas.pvt:
        ants: [15, 16, 17]
        sync_delay: 100
    snap06.sas.pvt:
        ants: [18, 19, 20]
        sync_delay: 120
    snap07.sas.pvt:
        ants: [21, 22, 23]
        sync_delay: 140


# Data is sent assuming a total of 32 Xengines and 
# a maximum of 48 channels per Xengine. If all the 
# 32 Xengines are not defined, the corresponding channels
# are not sent anywhere.
xengines:
    8:
        even:
           ip: "10.41.0.60"
           mac: 0x00163e445cde
        odd:
           ip: "10.41.0.60"
           mac: 0x00163e445cde
        chan_range: [4096, 4480]
    9:
        even:
           ip: "10.41.0.61"
           mac: 0x00163e758417
        odd:
           ip: "10.41.0.61"
           mac: 0x00163e758417
        chan_range: [4480, 4864]
    10:
        even:
           ip: "10.41.0.64"
           mac: 0x00163e3b9f59
        odd:
           ip: "10.41.0.64"
           mac: 0x00163e3b9f59
        chan_range: [4864, 5248]
    11:
        even:
           ip: "10.41.0.65"
           mac: 0x00163e015616 
        odd:
           ip: "10.41.0.65"
           mac: 0x00163e015616
        chan_range: [5248, 5632]
