# ETCD config file.
# birch
#endpoints: ["192.168.2.42:2379"]
# comap-spectrometer
#endpoints: ["192.168.2.73:2379"]
# dsamaster
#endpoints: ["192.168.1.132:2379"]
# dsa110
endpoints: ["etcdv3service.sas.pvt:2379"]
# Number of seconds for timeout
timeout: "1s"
# command to watch
corr_command: '/cmd/corr/'
snap_command: '/cmd/snap/'
#Simulation indicator(bool), True when in sim mode, False when using real hardware
SIM: False
