adc_samples_per_spectra: 8192
channels_per_sideband: 1024
fft_shift_noise: 1023
delay_filename: /mnt/nfs/runtime/delays.dat
utc_start_filename: /mnt/nfs/runtime/UTC_START.txt
fpga_bof: dsa_10gv11s.bof
snap:
  1:
    ip: 10.10.1.2
    adc_demux: 2
    adc_gain: 5
    src:
      - ip_base: 10.10.5.2
        port: 4002
      - ip_base: 10.10.3.2
        port: 4002
    dest:
      - ip: 10.10.5.1
        # 40175247655025 // ens6d1 on dsamaster
        mac: 24:8a:07:5d:80:71
        port: 4011
      - ip: 10.10.3.1
        #  40175247654465 ens6d1 on dsa5
        mac: 24:8a:07:5d:7e:41
        port: 4011
    coeff_filename: /mnt/nfs/runtime/snap1_coeffs.dat
  2:
    ip: 10.10.1.3
    adc_demux: 2
    adc_gain: 5
    src:
      - ip_base: 10.10.6.2
        port: 4002
      - ip_base: 10.10.3.3
        port: 4003
    dest:
      - ip: 10.10.6.1
        # 40175247654497 ens6d1 on dsa1 
        mac: 24:8a:07:5d:7e:61
        port: 4011
      - ip: 10.10.3.1
        # 40175247654465 ens6d1 on dsa5
        mac: 24:8a:07:5d:7e:41
        port: 4012
    coeff_filename: /mnt/nfs/runtime/snap2_coeffs.dat
  3:
    ip: 10.10.1.4
    adc_demux: 2
    adc_gain: 5
    src:
      - ip_base: 10.10.7.2
        port: 4002
      - ip_base: 10.10.3.4
        port: 4004
    dest:
      - ip: 10.10.7.1
        # 137432781157265 ens6d1 on dsa2
        mac: 7c:fe:90:19:f3:91
        port: 4011
      - ip: 10.10.3.1
        # 40175247654465 ens6d1 on dsa5
        mac: 24:8a:07:5d:7e:41
        port: 4013
    coeff_filename: /mnt/nfs/runtime/snap3_coeffs.dat
  4:
    ip: 10.10.1.5
    adc_demux: 2
    adc_gain: 5
    src:
      - ip_base: 10.10.8.2
        port: 4002
      - ip_base: 10.10.3.5
        port: 4005
    dest:
      - ip: 10.10.8.1
        # 137432781157249 ens6d1 on dsa3 
        mac: 7c:fe:90:19:f3:81
        port: 4011
      - ip: 10.10.3.1
        # 40175247654465 ens6d1 on dsa5
        mac: 24:8a:07:5d:7e:41
        port: 4014
    coeff_filename: /mnt/nfs/runtime/snap4_coeffs.dat
  5:
    ip: 10.10.1.6
    adc_demux: 2
    adc_gain: 5
    src:
      - ip_base: 10.10.9.2
        port: 4002
      - ip_base: 10.10.3.6
        port: 4006
    dest:
      - ip: 10.10.9.1
        # 137432781168273 ens6d1 on dsa4 
        mac: 7c:fe:90:1a:1e:91
        port: 4011
      - ip: 10.10.3.1
        # 40175247654465 ens6d1 on dsa5
        mac: 24:8a:07:5d:7e:41
        port: 4015
    coeff_filename: /mnt/nfs/runtime/snap5_coeffs.dat
